### ISSUE TITLE
Can not work with Mono

### ISSUE THREAD

**Issue by andras-tim** [victor-rds/KeeTrayTOTP#5] opened 2016-09-01 17:15 UTC
**Ubuntu:**

```
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
```

**Mono:**

```
Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen
```

**Error:**
![screenshot_2016-09-01_19-14-58](https://cloud.githubusercontent.com/assets/619016/18177005/70cfeaae-7078-11e6-87c7-db3ec7e06cd7.png)

**Comment by beatstick** [comment] 2016-11-22 10:25
It seems there is a workaround for TrayOTP in combination with keebuntu: 
https://github.com/dlech/Keebuntu/issues/31
Maybe this could be applied to keetraytotp as well, as it is based on Traytotp?

**Comment by skolarianer** [comment] 2017-05-26 21:44
Try this one and let me know …
https://github.com/skolarianer/KeeTrayTOTP/releases/tag/0.9.1-Beta

It’s working fine for me on Ubuntu 16.04. But I’m not sure if this breaks something on Windows. That’s why I haven’t made a PR yet.

**Comment by beatstick** [comment] 2017-05-30 18:50
I can confirm the plugin is working for me on xubuntu 16.04. No more plugin errors and I can log into steam using the provided otp-key.

**Comment by andras-tim** [comment] 2017-12-11 11:36
@victor-rds, can you release this fix?

**Comment by andras-tim** [comment] 2017-12-11 19:21
@skolarianer, the v0.9.1 has other problem:
The list of TOTP entries is loaded multiple times to the tray menu. _(click to the tray icon multiple times when you have least one TOTP)_

**Comment by skolarianer** [comment] 2017-12-11 23:06
@andras-tim, I recently switched to KeePassXC (https://keepassxc.org) with its native TOTP support. TOTP was added shortly after my fix in late June 2017. Steam support has been added several days ago and it’s planned to be released with v2.3.0 in a few days. https://github.com/keepassxreboot/keepassxc/pull/1206

**Comment by andras-tim** [comment] 2017-12-12 00:15
@skolarianer, thank you for your fast answer. I like the KeePassXC project, but currently, I much love the original KeePass, because this is more advanced, more customizable, ...

I'm waiting for KeePassXC be better or waiting for you fix this small bug in this plugin :wink:

**Comment by victor-rds** [comment] 2017-12-12 11:02
@andras-tim I was kinda busy the whole year and abandoned this project, I will take look and try to release the fix before the weekend.
Soon I will get my vacations and rewrite the whole thing  :sweat_smile:

**Comment by Sanaki** [comment] 2018-04-25 10:54
Just set up keepass2 on mono, looks like everything works cleanly (as long as mono is up to date, 4.2 was a nightmare, 5.10 works like a dream) except that using the replacement tray icons from [Keebuntu](https://github.com/dlech/Keebuntu), you still see duplicate entries in the list as @andras-tim mentioned back in December. I assume this isn't a bug from Keebuntu, but since the tray icon is entirely unusable without it, it's a bit hard to double check that.

**Closed** 2020-02-07 14:49 UTC
Labels: bug
