### ISSUE TITLE
Plug-in version 0.97-Beta won't load with KeePass 2.42, error "Index was outside the bounds of the array."

### ISSUE THREAD

**Issue by Contik** [victor-rds/KeeTrayTOTP#32] opened 2019-05-01 14:21 UTC
Hi,

on Windows 10 64-bit version 1803 (Build 17134.706) latest [KeePass 2.42 from earlier today, 05/01/2019 at 12:12:31 pm UTC](https://sourceforge.net/projects/keepass/files/KeePass%202.x/2.42/) won't load plug-in version 0.97-Beta. KeePass produces the following error pop-up (on a Windows install with German UI language):

![Error "Index was outside the bounds of the array." when loading plug-in version 0.97-Beta with KeePass 2.42](https://i.imgur.com/vH7rXzJ.png)

The `[Expanded Information]`block in Google-Translate-assisted English should read something like this:
```
[Expanded Information]
Index was outside the bounds of the array.
KeeTrayTOTP
   at KeeTrayTOTP.KeeTrayTOTPExt.Initialize(IPluginHost host)
   at KeePass.Plugins.PluginManager.LoadPlugins(List`1 lFiles, String strTypeName, String strDisplayFilePath, Boolean bSkipCacheFiles)
Boolean Initialize(KeePass.Plugins.IPluginHost)

[V] Details  [OK]
```
Can you please make KeeTrayTOTP's beta compatible with KeePass 2.42?

Thank you!

**Comment by robinvanpoppel** [comment] 2019-05-01 16:01
I'll need to dig in further to create a fix. What I for now could find was that it is crashing inside the Initialize plugin in the part where it is creating menu items. It's looking for an element with the name `m_ctxEntryMassModify`, but apparently that is gone / renamed in this new version.

**Comment by Contik** [comment] 2019-05-01 18:37
Got it, thanks for the heads-up!

**Comment by alexanderino** [comment] 2019-05-02 04:52
I have [notified KeePass's author of this issue](https://sourceforge.net/p/keepass/discussion/329220/thread/5ef408ed35/?page=1&limit=25#f331).

**Comment by robinvanpoppel** [comment] 2019-05-02 05:55
It has to do with this item in the release notes on 2.42. 
> Added main menu items 'Group', 'Entry' and 'Find', which contain all commands related to groups and entries (supersets of context menus); removed 'Edit' main menu item, because all of its commands are included in the three new main menu items.

As this plugin was adding to the menu's that are now gone, we need to find a new location for some of the actions that used to be under. [Code](https://github.com/victor-rds/KeeTrayTOTP/blob/6a82a4801cd589ff7b83cfbe02603d0dc2703544/TrayTOTP_Plugin.cs#L251) 

I hope to provide a fix this weekend. For now the workaround is to use the previous version of KeePass (2.41) until it is resolved in this plugin.

**Comment by robinvanpoppel** [comment] 2019-05-04 15:21
This took a bit more effort than I expected. As stated before the menu items changed quite a bit, and this plugin did not follow the guidelines for menu items as listed in the section [Providing Menu Items](https://keepass.info/%0D/help/v2_dev/plg_index.html). To work around it and follow the guidelines some menu items had to move inside of a subitem. I've attached a work in progress version here which should run with 2.41 and 2.42. 

I'd appreciate if you could let me know whether this is a workable solution, and whether you encounter any other issues as I had to change a lot of stuff around. If it is stable enough, I'll merge it into master and "officially" release a version.

[KeeTrayTOTP.zip](https://github.com/victor-rds/KeeTrayTOTP/files/3144503/KeeTrayTOTP.zip)

**Comment by Contik** [comment] 2019-05-04 18:30
This version works for me, I have everything I wanted :) Thanks!

**Comment by hulmgulm** [comment] 2019-05-04 18:32
Works for me too. Thank you!

**Comment by alexanderino** [comment] 2019-05-04 18:53
Quick update: about 5 minutes of testing shows the new version works, both with 2.42 and the just-released 2.42.1.

- KeeTrayTOTP items and sub-items are restored, under both right-click and 'Entry' menus
- Functionality (QR Code, Edit) all work again (did not scan QR code)
- TOTP column now displays TOTP again (screenshot 2)

So I'd conclude your fix works like a charm. Many thanks! If anything comes up, I'll post updates.

Screenshot 1 (Entry menu):
![keetraytotp-2 42 1-2](https://user-images.githubusercontent.com/7845069/57183504-54c6d000-6ef1-11e9-93da-7c7bdc7df266.png)

Screenshot 2 (context):
![keetraytotp-2 42 1-1](https://user-images.githubusercontent.com/7845069/57183502-52647600-6ef1-11e9-826a-51855e8bde17.png)

**Comment by haidelber** [comment] 2019-05-04 19:36
Works as expected. Thanks a lot!

**Comment by thakyZ** [comment] 2019-05-04 19:48
Is this normal? Or how do I fix?
![KeePass_2019-05-04_12-47-34](https://user-images.githubusercontent.com/950594/57184076-da536d00-6e6a-11e9-8842-70ee03f05338.png)
![2019-05-04_12-47-53](https://user-images.githubusercontent.com/950594/57184077-db849a00-6e6a-11e9-8448-0280017d72c6.png)

**Comment by woble** [comment] 2019-05-05 06:39
Works just fine here. Noticed that the new build is ~16KB smaller. What gives?

**Comment by addy90** [comment] 2019-05-05 11:24
Work fine here, too! Thank you a lot!

**Comment by robinvanpoppel** [comment] 2019-05-05 13:43
> 
> 
> Is this normal? Or how do I fix?
> ![2019-05-04_12-49-07](https://user-images.githubusercontent.com/950594/57184087-066eee00-6e6b-11e9-814d-428138744894.png)
> 
> ![2019-05-04_12-47-53](https://user-images.githubusercontent.com/950594/57184077-db849a00-6e6a-11e9-8448-0280017d72c6.png)

The only way I could reproduce the double menu this was having two plgx files for the plugin in the `plugins` folder. Can you check your plugins folder for duplicates?

**Comment by robinvanpoppel** [comment] 2019-05-05 13:45
> 
> 
> Works just fine here. Noticed that the new build is ~16KB smaller. What gives?

Yeah, I used PlgxTool to build the new plugin, and apparently it's a bit smaller. Thanks for the feedback! I'll merge this to master and formally release it.

**Closed by robinvanpoppel** 2019-05-05 13:45 UTC
